apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-fund1-web-dep
  namespace: corda-fac
  labels:
    app: node-fund1-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-fund1-web
  template:
    metadata:
      labels:
        app: node-fund1-web
    spec:
      containers:
      - name: node-fund1-web
        image: crodaaks.azurecr.io/fund-administrator:v3.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
          name: port1
        resources:
          requests:
            cpu: 500m
            memory: 1G
          limits:
            cpu: 1000m
            memory: 1512M

---
apiVersion: v1
kind: Service
metadata:
  name: node-fund1-web-svc
  namespace: corda-fac
spec:
  selector:
    app: node-fund1-web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer