---
apiVersion: v1
kind: Service
metadata:
  name: node-fund1-svc
  namespace: corda-fac
spec:
  selector:
    app: node-fund1
  ports:
  - port: 10005
    targetPort: 10005
    name: port-1
  - port: 30005
    targetPort: 30005
    name: port-2
  - port: 2223
    targetPort: 2223
    name: port-3
  - port: 17704
    targetPort: 17704
    name: port-4
  type: LoadBalancer