apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-fundmanger-dep
  namespace: corda-fac
  labels:
    app: node-fundmanger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-fundmanger
  template:
    metadata:
      labels:
        app: node-fundmanger
    spec:
      containers:
      - name: node-fundmanger
        image: crodaaks.azurecr.io/fac_corda:v4.7
        imagePullPolicy: "Always"
        ports:
        - containerPort: 10005
          name: port1
        - containerPort: 30005
          name: port2
        - containerPort: 2223
          name: port3
        - containerPort: 17704
          name: port4
        resources:
          requests:
            cpu: 500m
            memory: 1G
          limits:
            cpu: 1000m
            memory: 1512M
        env:
        - name: sleeps
          value: "1"
        - name: LOGPATH
          value: /opt/logs
        - name: LOGSTASH
          value: 10.244.4.76
        - name: IDENTITY_HOST 
          value: 20.68.121.136
        - name: IDENTITY_PORT
          value: "10000"
        - name: NETWORK_MAP_HOST
          value: 20.68.122.69
        - name: NETWORK_MAP_PORT
          value: "10000"
        - name: PUBLIC_HOST
          value: 10.44.54.15
        - name: P2P_PORT
          value: "30005"
        - name: MIGRATION_MODE
          value: "false"
        volumeMounts:
        - mountPath: /opt/corda/persistent
          name: corda-node-2-pv
        - mountPath: /opt/corda/persistent/log4j2.xml
          name: node-config-volume
          readOnly: false
          subPath: log4j2.xml
        - mountPath: /opt/corda/persistent/node.conf
          name: node-config-volume
          readOnly: false
          subPath: node.conf
        - mountPath: /opt/corda/persistent/trust-stores/networkRootTrustStore.jks
          name: node-config-volume
          readOnly: false
          subPath: networkRootTrustStore.jks
      volumes:
      - name: corda-node-2-pv
        persistentVolumeClaim:
          claimName: corda-node-fundmanger-pvc
      - configMap:
          defaultMode: 0777
          name: corda-node-fundmanger-configmap
        name: node-config-volume
